site_name: Revision Notes

theme:
  name: readthedocs

docs_dir: revision_notes_GCSE

nav:
  - Biology: Biology/
  - Chemistry: Chemistry/
  - Physics: Physics/

markdown_extensions:
  - toc:
      permalink: true
  - fenced_code
